### ISSUE TITLE
Public Member Profile doesn't display profile image

### ISSUE THREAD

**Issue by zaudtke** [ThatConference/that-website#465] opened 2020-03-25 17:38 UTC
when I visit my own member page when Not logged in, I don't see my profile image.

1.  Log in
2. go to https://www.thatconference.com/member/alzaudtke
3. See image
4. Log out
5. go to https://www.thatconference.com/member/alzaudtke
6. No Profile image, only place holder
7.  Went to Clark's profile https://www.thatconference.com/member/clark no image, logged in or not

**Comment by csell5** [comment] 2020-03-25 19:27
@brettski did our conversion to CloudRun screw up the dns entries for this?

**Comment by brettski** [comment] 2020-03-25 19:33
It should have had no affect. Investigating.

**Comment by brettski** [comment] 2020-03-25 19:41
The issue is because the public query doesn't include profileImage:
```graphql
  const GET_MEMBER_PUBLIC = gql`
    query getMember {
      members {
        member(slug: "${slug}") {
          id
          bio
          firstName
          lastName
          company
          jobTitle
          profileSlug
          profileLinks {
            isPublic
            linkType
            url
          }
          interests
        }
      }
    }
  `;
```

I will look into submitting a fix for this.

**Comment by csell5** [comment] 2020-03-25 19:54
that would do it.

**Comment by brettski** [comment] 2020-03-25 20:01
Fixed in PR #466

**Comment by mcookWI** [comment] 2020-03-25 20:01
Now seeing public profile images of other users when logged in or out.

**Closed by brettski** 2020-03-25 20:01 UTC
Labels: bug
